[workspace]
members = ["nptk-core", "nptk-macros", "nptk-theme", "nptk-widgets", "examples/*"]

[workspace.package]
version = "0.5.0"
edition = "2021"
authors = ["Dominik Adrian Grzywak <starterx4@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Nepsod/nptk"
homepage = ""
categories = ["gui", "graphics", "rendering", "virtualization", "rendering::engine"]
keywords = ["ui", "gui", "interface", "graphics", "user-interface"]

[workspace.dependencies]
bytemuck = "1.23.0"
peniko = "0.5.0"
nalgebra = { version = "0.33.2", default-features = false, features = ["std"] }
indexmap = "2.9.0"
log = "0.4.27"
nptk-core = { version = "0.5.0", path = "nptk-core" }
nptk-macros = { version = "0.5.0", path = "nptk-macros" }
nptk-theme = { version = "0.5.0", path = "nptk-theme" }
nptk-widgets = { version = "0.5.0", path = "nptk-widgets" }

[package]
name = "nptk"
description = "Lightning fast and powerful UI Framework for Rust."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
nptk-core = { workspace = true }
nptk-theme = { workspace = true }
nptk-widgets = { workspace = true }
nptk-macros = { workspace = true, optional = true }
peniko = { workspace = true }
nalgebra = { workspace = true }

[features]
default = ["macros"]

# Exports useful macros for working with nptk.
macros = ["nptk-macros"]

# Exports `vello` and `skrifa` for drawing vector graphics. Useful if you want to create custom widgets.
vg = ["nptk-core/vg"]

# Enables the `Canvas` widget for drawing to the screen.
canvas = ["nptk-widgets/canvas"]

# Use the `tokio` runtime for running tasks inside a task runner.
tokio-runner = ["nptk-core/tokio-runner"]

[lib]
name = "nptk"
path = "src/lib.rs"
