[package]
name = "nptk-core"
description = "Core Functionality for nptk UI => See the `nptk` crate for more."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
winit = "0.30.9"
wgpu-types = "23.0.0"
wgpu = "26.0.1"
vello = "0.4.1"
vello_hybrid = "0.0.4"
vello_common = "0.0.4"
taffy = "0.8.1"
bitflags = "2.9.0"
skrifa = { version = "0.30.0", optional = true }
arc-swap = "1.7.1"
parking_lot = "0.12.3"
pollster = "0.3.0"
tokio = { version = "1.35.1", features = ["parking_lot", "rt-multi-thread"], optional = true }
nptk-theme = { workspace = true }
nalgebra = { workspace = true }
indexmap = { workspace = true }
peniko = "0.1.1"
log = "0.4.21"
read-fonts = "0.29.2"
parley = "0.5.0"
fontique = "0.5.0"
harfrust = "0.2.0"

[target.'cfg(target_os = "linux")'.dependencies]
smithay-client-toolkit = "0.18"
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["client"] }
wayland-protocols-plasma = { version = "0.2", features = ["client"] }
raw-window-handle = "0.6"
tempfile = "3.10.1"

[features]
default = []
vg = ["skrifa"]
tokio-runner = ["tokio"]
vello-vg = []