[package]
name = "value_input"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
nptk = { path = "../../" }
nptk-core = { path = "../../nptk-core" }
nptk-widgets = { path = "../../nptk-widgets" }
