[package]
name = "file_list"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nptk = { path = "../.." }
nptk-theme = { path = "../../nptk-theme" }
nptk-widgets = { path = "../../nptk-widgets" }
tokio = { version = "1.35", features = ["rt-multi-thread", "macros"] }
